const campusHeartbeatAssets = [
  "Animal Science",
  "Arena Auditorium",
  "Arts and Sciences",
  "Aven Nelson",
  "Berry Center",
  "Beta House",
  "Biological Sciences",
  "Centennial Complex",
  "Central Energy Plant",
  "Centrex",
  "Cheney Center",
  "Child Care",
  "Classroom Building",
  "Coe Library",
  "College of Agriculture",
  "College of Business",
  "College of Education",
  "Engineering",
  "College of Law",
  "Corbett",
  "Earth Sciences",
  "Education Annex",
  "Energy Innovation Center",
  "Fieldhouse",
  "Fieldhouse North",
  "Fine Arts",
  "Gateway Center",
  "General Storage",
  "Geological Survey",
  "Geology",
  "HAPC and RAC",
  "Half Acre Gym",
  "Health Science and Pharmacy",
  "High Bay",
  "Hoyt Hall",
  "Information Technology",
  "Indoor Practice Facility",
  "Knight Hall",
  "McWhinnie Hall",
  "Merica Hall",
  "Old Main",
  "Physical Science",
  "RMMC",
  "Ross Hall",
  "Service Building",
  "Stadium",
  "Vet Lab",
  "Visual Arts",
  "WRI and Bureau of Mines",
  "WTBC",
  "Williams Conservatory",
  "Wyoming Hall",
  "Student Union",
];

module.exports = { campusHeartbeatAssets };
