services:
  hb-pg-db:
    container_name: hb-pg-db
    build: ./db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
    volumes:
      - ./db:/db
      - ./data:/data
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/init_complete"]
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 60s
  hb-pg-admin:
    container_name: hb-pg-admin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      hb-pg-db:
        condition: service_healthy
    links:
      - hb-pg-db
    tty: true
  hb-api:
    container_name: hb-api
    build: 
      context: ./api
      dockerfile: Dockerfile
      args:
        - DEV_MODE=${API_DEV_MODE}
    volumes:
      - "./api:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      # postgres://<user>:<password>@hb-pg-db:5432/<pg_db_name>
      - DATABASE_URL=postgres://${PG_DB_USER}:${PG_DB_PASSWORD}@hb-pg-db:5432/${PG_DB}
      - CLIENT_APP_URL=${API_CLIENT_APP_URL}
      - PORT=${API_PORT}
      - DEV_MODE=${API_DEV_MODE}
    depends_on:
      hb-pg-db:
        condition: service_healthy
    links:
      - hb-pg-db