--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2024-04-17 16:29:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 239 (class 1255 OID 74323)
-- Name: insert_child_assets(text[]); Type: PROCEDURE; Schema: public; Owner: -
--

CREATE PROCEDURE public.insert_child_assets(IN assets text[])
    LANGUAGE plpgsql
    AS $$
DECLARE
    isActive BOOLEAN;
    asset_name TEXT;
    asset_short_name TEXT;
    parent_name TEXT;
    parent_tree_id INTEGER;
    parent_left INTEGER;
BEGIN

    FOR i IN 1..ARRAY_LENGTH(assets, 1)
    LOOP

      isActive := assets[i][1];
      asset_name := assets[i][2];
      asset_short_name := assets[i][3];
      parent_name := assets[i][4];

      SELECT tree_id
      INTO parent_tree_id
      FROM asset WHERE asset.name = parent_name;

      SELECT lft
      INTO parent_left
      FROM asset WHERE asset.name = parent_name;

      UPDATE asset
      SET rght = rght + 2
      WHERE rght > parent_left
      AND tree_id = parent_tree_id;

      UPDATE asset
      SET lft = lft + 2
      WHERE lft > parent_left
      AND tree_id = parent_tree_id;

      INSERT INTO asset
      (name, short_name, lft, rght, active, tree_id)
      VALUES
      (asset_name, asset_short_name, parent_left+1, parent_left+2, isActive, parent_tree_id);

    END LOOP;
END;
$$;


--
-- TOC entry 238 (class 1255 OID 74325)
-- Name: insert_into_measurement(); Type: PROCEDURE; Schema: public; Owner: -
--

CREATE PROCEDURE public.insert_into_measurement()
    LANGUAGE plpgsql
    AS $$
BEGIN

    INSERT INTO measurement
    (asset_id, commodity_id, ts, value)
    SELECT asset_id, commodity_id, ts, value FROM measurement_copy
    WHERE asset_id IS NOT NULL;

END;
$$;


--
-- TOC entry 236 (class 1255 OID 74322)
-- Name: insert_parent_assets(text[]); Type: PROCEDURE; Schema: public; Owner: -
--

CREATE PROCEDURE public.insert_parent_assets(IN assets text[])
    LANGUAGE plpgsql
    AS $$
DECLARE
    isActive BOOLEAN;
    asset_name TEXT;
    asset_short_name TEXT;
    left_value INTEGER;
    right_value INTEGER;
BEGIN

    FOR i IN 1..ARRAY_LENGTH(assets, 1)
    LOOP

        isActive := 'true';
        asset_name := assets[i];
        asset_short_name := assets[i];
        left_value := 1;
        right_value := 2;

        INSERT INTO asset(name, short_name, lft, rght, active)
        VALUES
        (asset_name, asset_short_name, left_value, right_value, isActive);

    END LOOP;
END;
$$;


--
-- TOC entry 237 (class 1255 OID 74324)
-- Name: update_measurement_foreign_keys(); Type: PROCEDURE; Schema: public; Owner: -
--

CREATE PROCEDURE public.update_measurement_foreign_keys()
    LANGUAGE plpgsql
    AS $$
BEGIN

    UPDATE measurement_copy
    SET asset_id = (SELECT id FROM asset WHERE name = bldgname);

    UPDATE measurement_copy
    SET commodity_id = (SELECT id FROM commodity WHERE type = commodity_type);

END;
$$;


SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 74356)
-- Name: asset; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asset (
    id integer NOT NULL,
    active boolean NOT NULL,
    name character varying(255) NOT NULL,
    short_name character varying(255) NOT NULL,
    tree_id integer NOT NULL,
    lft integer NOT NULL,
    rght integer NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 74354)
-- Name: asset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 74355)
-- Name: asset_tree_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asset ALTER COLUMN tree_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_tree_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 74347)
-- Name: commodity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.commodity (
    id integer NOT NULL,
    type character varying(255) NOT NULL
);


--
-- TOC entry 216 (class 1259 OID 74346)
-- Name: commodity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.commodity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commodity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 74377)
-- Name: measurement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.measurement (
    id integer NOT NULL,
    asset_id integer NOT NULL,
    commodity_id integer NOT NULL,
    ts timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    value numeric NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 74376)
-- Name: measurement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.measurement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.measurement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 74364)
-- Name: metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metadata (
    id integer NOT NULL,
    asset_id integer NOT NULL,
    data jsonb NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 74363)
-- Name: metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3201 (class 2606 OID 74362)
-- Name: asset asset_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset
    ADD CONSTRAINT asset_pkey PRIMARY KEY (id);


--
-- TOC entry 3197 (class 2606 OID 74351)
-- Name: commodity commodity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commodity
    ADD CONSTRAINT commodity_pkey PRIMARY KEY (id);


--
-- TOC entry 3199 (class 2606 OID 74353)
-- Name: commodity commodity_type_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commodity
    ADD CONSTRAINT commodity_type_key UNIQUE (type);


--
-- TOC entry 3206 (class 2606 OID 74384)
-- Name: measurement measurement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT measurement_pkey PRIMARY KEY (id);


--
-- TOC entry 3204 (class 2606 OID 74370)
-- Name: metadata metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metadata
    ADD CONSTRAINT metadata_pkey PRIMARY KEY (id);


-- --
-- -- TOC entry 3202 (class 1259 OID 74395)
-- -- Name: name_index; Type: INDEX; Schema: public; Owner: -
-- --

-- CREATE INDEX name_index ON public.asset USING btree (name);


--
-- TOC entry 3208 (class 2606 OID 74385)
-- Name: measurement measurement_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT measurement_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.asset(id);


--
-- TOC entry 3209 (class 2606 OID 74390)
-- Name: measurement measurement_commodity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT measurement_commodity_id_fkey FOREIGN KEY (commodity_id) REFERENCES public.commodity(id);


--
-- TOC entry 3207 (class 2606 OID 74371)
-- Name: metadata metadata_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metadata
    ADD CONSTRAINT metadata_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.asset(id);


-- Completed on 2024-04-17 16:29:01

--
-- PostgreSQL database dump complete
--


\copy public.asset FROM '/db_data/asset.csv' DELIMITER '|' CSV HEADER NULL AS '';

--
-- TOC entry 3202 (class 1259 OID 74395)
-- Name: name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index ON public.asset USING btree (name);


\copy public.commodity FROM '/db_data/commodity.csv' DELIMITER '|' CSV HEADER NULL AS '';
-- \copy public.metadata FROM '/db_data/metadata.csv' DELIMITER '|' CSV HEADER NULL AS '';
\copy public.measurement FROM '/db_data/measurement.csv' DELIMITER '|' CSV HEADER NULL AS '';


