SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 74356)
-- Name: asset; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asset (
    id integer NOT NULL,
    active boolean NOT NULL,
    name character varying(255) NOT NULL,
    short_name character varying(255) NOT NULL,
    tree_id integer NOT NULL,
    lft integer NOT NULL,
    rght integer NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 74354)
-- Name: asset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 74355)
-- Name: asset_tree_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asset ALTER COLUMN tree_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_tree_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 74347)
-- Name: commodity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.commodity (
    id integer NOT NULL,
    type character varying(255) NOT NULL
);


--
-- TOC entry 216 (class 1259 OID 74346)
-- Name: commodity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.commodity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commodity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 74377)
-- Name: measurement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.measurement (
    id integer NOT NULL,
    asset_id integer NOT NULL,
    commodity_id integer NOT NULL,
    ts timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    value numeric NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 74376)
-- Name: measurement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.measurement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.measurement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 74364)
-- Name: metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metadata (
    id integer NOT NULL,
    asset_id integer NOT NULL,
    data jsonb NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 74363)
-- Name: metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3201 (class 2606 OID 74362)
-- Name: asset asset_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset
    ADD CONSTRAINT asset_pkey PRIMARY KEY (id);


--
-- TOC entry 3197 (class 2606 OID 74351)
-- Name: commodity commodity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commodity
    ADD CONSTRAINT commodity_pkey PRIMARY KEY (id);


--
-- TOC entry 3199 (class 2606 OID 74353)
-- Name: commodity commodity_type_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commodity
    ADD CONSTRAINT commodity_type_key UNIQUE (type);


--
-- TOC entry 3206 (class 2606 OID 74384)
-- Name: measurement measurement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT measurement_pkey PRIMARY KEY (id);


--
-- TOC entry 3204 (class 2606 OID 74370)
-- Name: metadata metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metadata
    ADD CONSTRAINT metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 3202 (class 1259 OID 74395)
-- Name: name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index ON public.asset USING btree (name);


--
-- TOC entry 3208 (class 2606 OID 74385)
-- Name: measurement measurement_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT measurement_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.asset(id);


--
-- TOC entry 3209 (class 2606 OID 74390)
-- Name: measurement measurement_commodity_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT measurement_commodity_id_fkey FOREIGN KEY (commodity_id) REFERENCES public.commodity(id);


--
-- TOC entry 3207 (class 2606 OID 74371)
-- Name: metadata metadata_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metadata
    ADD CONSTRAINT metadata_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.asset(id);

