// Replaces question marks in the parameterized SQL format generated by `react-querybuilder`'s `formatQuery` with `$1`, `$2`, etc. to adhere to `pg`'s parameterized query format.
function processSQL(sql) {
  let i = 0;

  return sql.replace(/\?/g, () => `$${++i}`);
}

module.exports = { processSQL };
