FROM node:latest

# Set working directory.
RUN mkdir /usr/src/app
WORKDIR /usr/src

COPY constants /usr/src/app/constants
COPY get_routes /usr/src/app/get_routes
COPY index.js /usr/src/app/index.js
COPY lib /usr/src/app/lib
COPY routes /usr/src/app/routes
COPY utils /usr/src/app/utils

# Install and cache dependencies.
COPY package.json /usr/src/package.json
COPY package-lock.json /usr/src/package-lock.json
RUN npm install --no-progress

CMD ["npm", "start"]