FROM node:latest

# Set working directory.
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --no-progress

# Copy application code
COPY . .

# Start the application
CMD ["npm", "start"]